### ISSUE TITLE
PostgreSQL version: compatibility matrix vs doc

### ISSUE THREAD

**Issue by fpuga** [Giswater/giswater_dbmodel#11]
In the version compatibility matrix

https://github.com/Giswater/giswater_dbmodel/wiki/version-compatibility

seems like "any" postgresql version is supported.

But in the doc

https://giswater.gitbook.io/giswater_manual_es/2.-instalacion-y-puesta-en-marcha

there is a big warning that says that postgresql > 12 is no supported.

**Comment by albertbofill** [comment]
Hi @fpuga 

It's better to trust the compatibility matrix. Any version of postgres (since 9.5) is supported using Giswater 3.5, but we recommend 11 to 14. We're currently using 14 on our daily work.

The user's manual wasn't updated in this chapter. Now that's already fixed.

Thanks for reporting it.
