### ISSUE TITLE
PL/pgSQL function created but not available

### ISSUE THREAD

**Issue by dvgeo** [Giswater/giswater_dbmodel#32]
I'm trying to create a function in PL/pgSQL using the GISWATER plugin.Even following the steps in the tutorial https://github.com/Giswater/giswater_dbmodel/wiki/Create-new-PLpgSQL-function, the created function is not being displayed in the plugin toolbox in QGIS even when reloading the plugin.
![create function](https://github.com/user-attachments/assets/a381694d-5069-4b01-9b3f-41eb73867077)
![function](https://github.com/user-attachments/assets/ce26e0f9-1ecf-4cd0-8fde-2c8496cf87fa)
![function_pgadmin](https://github.com/user-attachments/assets/d197cf94-5a5d-4d48-bdd7-889f9dad2087)
![qgis](https://github.com/user-attachments/assets/93af8ad5-8177-46d2-9cdd-d120e87dd36b)

**Comment by edgarfuste** [comment]
Hello @dvgeo! Reviewing the problem you have had and checking the wiki documentation, I have seen that we do not refer any information to the “device” field, this is very important because it allows you to define on which device to display this function. If you are working in QGIS Desktop it is necessary to set this column with the value {4}. Once the device is defined, the function that you have configured will appear correctly. 

We will modify the wiki to add this information.

I am waiting for your response to see if this solves your problem or if there is still a problem, in this case let me know and we will check it.

Thanks!

**Comment by dvgeo** [comment]
It works!! Thank you @edgarfuste
